language: rust

sudo: required

rust:
  - 1.42.0

branches:
  only:
    - test-ci

addons:
  apt:
    packages:
      - ca-certificates
      - file
      - build-essential
      - autoconf
      - automake
      - autotools-dev
      - libtool
      - xutils-dev
      - cmake
      - pkg-config
      - libfreetype6-dev
      - libfontconfig1-dev
      - xclip

env:
  - TEST_DIR=engine
  - TEST_DIR=web
  - TEST_DIR=server

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 12.16
  - npm install yarn

before_script:
  - cd $TEST_DIR && cargo build --verbose --all
  - cd $TEST_DIR && yarn install
  - cd $TEST_DIR && npm install 

script: 
  - cargo test --verbose --all
  - yarn test --watchAll=false
  - npm run test 